include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    duplicate_import: ignore
    library_private_types_in_public_api: ignore
    no_leading_underscores_for_local_identifiers: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_final_fields: ignore
    sort_child_properties_last: ignore
    unnecessary_null_comparison: ignore
    unnecessary_to_list_in_spreads: ignore
    unused_element: ignore
    unused_field: ignore
    unused_import: ignore
    unused_local_variable: ignore
    use_build_context_synchronously: ignore
    use_key_in_widget_constructors: ignore
    use_super_parameters: ignore
